[package]
name = "pepeeltoro41/replecs"
version = "0.2.3"
description = "Networking library for Jecs"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = [
    "default.project.json",
    "src",
    "src/**",
    "wally.toml",
    "README.md",
    "LICENSE",
]
exclude = ["**"]

[dependencies]
b2 = "hardlyardi/b226@0.2.3"
