[package]
name = "pepeeltoro41/replecs-pepecs"
version = "0.0.1"
description = "Networking library for Pepecs"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = [
    "default.project.json",
    "src",
    "src/**",
    "wally.toml",
    "README.md",
    "LICENSE",
]
exclude = ["**"]

[dependencies]
pepecs = "pepeeltoro41/pepecs@0.0.2"
