name = "pepeeltoro41/replecs_demo"
authors = ["PepeElToro41"]
version = "0.0.1"

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[target]
build_files = ["src"]
environment = "roblox"
lib = "src/init.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }

[dependencies]
jecs = { wally = "ukendio/jecs", version = "^0.8.3" }
jabby = { wally = "alicesaidhi/jabby", version = "^0.3.1" }

[patches]
"wally#alicesaidhi/jabby" = { "0.3.1 roblox" = "patches/wally#alicesaidhi+jabby-0.3.1+roblox.patch" }
